"""
Core enumerations for SemaFS domain model.

This module defines the fundamental type system for the semantic filesystem,
including node types, lifecycle states, and operation types.
"""
from __future__ import annotations
from enum import Enum


class NodeType(str, Enum):
    """
    Node type classification in the semantic tree.

    SemaFS uses a two-type model similar to filesystems:
    - CATEGORY: Directory-like nodes that organize and group other nodes
    - LEAF: Terminal nodes that contain actual knowledge fragments
    """
    CATEGORY = "CATEGORY"  # Directory node that can contain children
    LEAF = "LEAF"          # Terminal node containing content


class NodeStatus(str, Enum):
    """
    Lifecycle status of a node in the knowledge tree.

    Nodes progress through states during the write-maintain cycle:
    - PENDING_REVIEW → PROCESSING → ACTIVE (normal flow)
    - Any state → ARCHIVED (when merged or superseded)

    State transition rules:
    - PENDING_REVIEW: Newly written fragments awaiting maintenance
    - PROCESSING: Currently being reorganized by the maintenance engine
    - ACTIVE: Stable, queryable knowledge fragments
    - ARCHIVED: Soft-deleted after merge/group operations
    """
    ACTIVE = "ACTIVE"                   # Stable, queryable node
    ARCHIVED = "ARCHIVED"               # Soft-deleted (retained for audit)
    PENDING_REVIEW = "PENDING_REVIEW"   # New fragment awaiting organization
    PROCESSING = "PROCESSING"           # Being reorganized by maintenance


class OpType(str, Enum):
    """
    Operation types for knowledge tree reorganization.

    These operations are generated by the Strategy and executed by the Executor:
    - MERGE: Combine semantically similar leaves into one
    - GROUP: Create a new category and move leaves into it
    - MOVE: Relocate a leaf to an existing category
    - PERSIST: Convert pending fragment to active leaf (rule-based only)
    """
    MOVE = "MOVE"       # Move leaf to existing category
    MERGE = "MERGE"     # Combine multiple leaves into one
    GROUP = "GROUP"     # Create new category and move leaves into it
    PERSIST = "PERSIST" # Convert PENDING_REVIEW to ACTIVE (no LLM)
